---
title: "Jeong Hwan Ko's resume"
author: Jeong Hwan Ko
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['cv.css', 'resume']
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> joanko35@gmail.com
- <i class="fa fa-linkedin"></i> [linkedin.com/in/jeong-hwan-ko](https://www.linkedin.com/in/jeong-hwan-ko/) 
- <i class="fa fa-github"></i> [github.com/joaaanko](https://github.com/joaaanko)
- <i class="fa fa-phone"></i> 06 58 54 14 65

Pour plus d'informations, vous pouvez me contacter par mail.

Programmation {#skills-Programmation}
--------------------------------------------------------------------------------

* Programmation en __R__ & __Python__.
* Ligne de commande avec __bash__.
* __Git__ & gestion de versions.

Data Science {#skills-datascience}
--------------------------------------------------------------------------------

- Manipulation, Traitement & Visualisation des données avec __R (tidyverse/ggplot)__ & __Python (numpy/pandas/matplotlib)__.
- Inférence et prédiction en utilisant des modèles de __Machine Learning__ paramétriques & non-paramétriques avec __scikit-learn__.
- __Deep Learning__ avec __Keras & Tensorflow__.
- Écritures de documents scientifiques en utilisant [Rmarkdown](https://rmarkdown.rstudio.com/), __LaTeX__ et __Jupyter Notebook__ (présentations/rapports automatiques/CV)

Langues {#skills-langues}
--------------------------------------------------------------------------------
* Français : courant
* Anglais : __C1 Advanced__, Cambridge English.
* Coréen : langue maternelle
* Polonais et Espagnol : intermédiaire

Centres d'intérêt {#skills-langues}
--------------------------------------------------------------------------------

* Violon - depuis 2005
* Basketball - niveau amateur et anciennement en club et en compétitif

Document généré le `r today <- Sys.Date();format(today, format="%d %B %Y")`.



Main
================================================================================

<b style='color:#2980b9'>J</b>eong <b style='color:#2980b9'>H</b>wan <b style='color:#2980b9'>K</b>o {#title}
--------------------------------------------------------------------------------

### Recherche d'emploi en data science pour 3e trimestre 2024. 

A la recherche d'un emploi dans le domaine de la Data Science - Intelligence Artificielle, pour commencer à l'issu de mes expériences en recherche en Statistique Appliquée.

Expérience Professionnelle {data-icon=suitcase}
--------------------------------------------------------------------------------
### Doctorant en Statistique Appliquée

INRAE

Toulouse & Jouy-en-Josas, France

2023 - Présent

__Compétences générales__ :

- Présentations & Rédaction de résultats de recherche.
- Veille bibliographique  et vulgarisation scientifique.
- Traitement, Analyse, Inférence Visualisation de données.

__Communications & Enseignements__ : 

- Présentation aux __Journées de la Statistique de la SFdS__
- __Enseignement__ de statistique descriptive et clustering

### Data Scientist

Capgemini Engineering

Toulouse, France

2023

- Implémentation d'algorithmes de Computer Vision pour guider un utilisateur à la bonne utilisation d'un inhalateur via __Deep Learning__
- Méthode __Agile__

### Data Scientist

Caisse d'Epargne Midi-Pyréenées

Toulouse, France

2021-2022

- Implémentation de modèles de prédiction d'appétence à un investissement immobilier par méthodes de Machine Learning. 
- Data Mining de données publiques afin de mettre en place des stratégies d'investissement immobilier écologiques


### Ingénieur en traitement d'images

Comité International de la Croix Rouge.

Toulouse, France

2021

Développement d'algorithmes automatiques et semi-automatiques de traitement d'images en Python pour l'identification des personnes disparues, incluant alignement, centrage de visage, suppression de l'arrière-plan et synthétisation d'images avec des réseaux de neurones.

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Diplôme d'ingénieur en Mathématiques Appliquées

INSA Toulouse

Toulouse, France

2017 - 2022

Statistique Appliquée, Modélisation statistique, traitement d'image, Machine & Deep Learning

### Baccalauréat Scientifique - Mention Très Bien

Lycée Français de Varsovie 

Varsovie, Pologne

2004 - 2017