---
title: "Jeong Hwan Ko's resume"
author: Jeong Hwan Ko
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['cv.css', 'resume']
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
# knit: pagedown::chrome_print
---

Aside
================================================================================
_Nationalité française_

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> joanko35@gmail.com
- <i class="fa fa-linkedin"></i> [linkedin.com/in/jeong-hwan-ko](https://www.linkedin.com/in/jeong-hwan-ko/) 
- <i class="fa fa-github"></i> [github.com/joaaanko](https://github.com/joaaanko)
- <i class="fa fa-phone"></i> 06 58 54 14 65

Pour plus d'informations, vous pouvez me contacter par mail.

Programmation {#skills-Programmation}
--------------------------------------------------------------------------------

* Programmation en __R__ & __Python__.
* Ligne de commande avec __bash__.
* __Git__ & gestion de versions.

Data Science {#skills-datascience}
--------------------------------------------------------------------------------
- Base de données avec __SQL__.
- Manipulation, Traitement & Visualisation des données avec __R (tidyverse/ggplot)__ & __Python (numpy/pandas/matplotlib, geopandas)__.
- Inférence et prédiction en utilisant des modèles de __Machine Learning__ paramétriques & non-paramétriques avec __scikit-learn__.
- __Deep Learning__ avec __Keras & Tensorflow__.
- Computer Vision avec __OpenCV__.
- Écritures de documents scientifiques en utilisant [Rmarkdown](https://rmarkdown.rstudio.com/), __LaTeX__ et __Jupyter Notebook__ (présentations/rapports automatiques)

Langues {#skills-langues}
--------------------------------------------------------------------------------
* Français, Coréen : courant
* Anglais : [C1 Advanced](https://www.cambridgeenglish.org/exams-and-tests/advanced/), Cambridge English.
* Polonais et Espagnol : intermédiaire

Centres d'intérêt {#skills-langues}
--------------------------------------------------------------------------------

* Violon - depuis 2005
* Basketball 

<!-- Document généré le `r today <- Sys.Date();format(today, format="%d %B %Y")`. -->



Main
================================================================================

<b style='color:#2980b9'>J</b>eong <b style='color:#2980b9'>H</b>wan <b style='color:#2980b9'>K</b>o {#title}
--------------------------------------------------------------------------------

### Data Scientist avec spécialité en Statistique et IA

Ingénieur en Mathématiques Appliquées avec un grand intérêt pour le développement et le traitement d'image, je cherche un CDI dans le domaine de la Data ou du développement logiciel.    

Expérience Professionnelle {data-icon=suitcase}
--------------------------------------------------------------------------------
### CDD, Analyse de la spécificité des associations génétiques dans les études multi-population

_INRAE_

Toulouse & Jouy-en-Josas, France

2023 - 2024

- Veille bibliographique, rédaction de résultats de recherche.
- Analyse de données biologiques, représentations graphiques et interprétation des résultats selon le contexte biologique, rédaction de documentation.
- [Abstract et présentation](https://hal.science/hal-04593233v1) aux __Journées de la Statistique de la Société Française de Statistique__
- __Enseignement__ de statistique descriptive et clustering aux étudiants en 3ème année de l'INSA Toulouse

### Data Scientist

_Capgemini Engineering_

Toulouse, France

2023

- Implémentation d'algorithmes de Computer Vision pour guider un utilisateur à la bonne utilisation d'un inhalateur via __Deep Learning__, en __Python__.
- Méthode __Agile__.

### Data Scientist

_Caisse d'Epargne Midi-Pyréenées_

Toulouse, France

2021-2022

- Implémentation de modèles de prédiction d'appétence à un investissement immobilier par méthodes de Machine Learning, __Python__. 
- Data Mining de données publiques afin de mettre en place des stratégies d'investissement immobilier écologiques, __Python__.


### Ingénieur en traitement d'images

_Comité International de la Croix Rouge_

Toulouse, France

2021

Développement et tests d'algorithmes en Python pour l'identification de personnes disparues : alignement, centrage de visage, suppression d'arrière-plan et synthèse d'images avec réseaux de neurones, __Python__, __C++__.

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Diplôme d'ingénieur en Mathématiques Appliquées

_INSA Toulouse_

Toulouse, France

2017 - 2022

Statistique Appliquée, Modélisation statistique, traitement d'image, Machine & Deep Learning, Actuariat

### Baccalauréat Scientifique - Mention Très Bien

_Lycée Français de Varsovie_

Varsovie, Pologne

2017